vim.keymap.set('n', '<leader>rn', vim.lsp.buf.rename)
vim.keymap.set('n', '<leader>ca', vim.lsp.buf.code_action)
vim.keymap.set('n', '<leader>gd', vim.lsp.buf.definition)
vim.keymap.set('n', '<leader>gD', vim.lsp.buf.declaration)
vim.keymap.set('n', '<leader>D', vim.lsp.buf.type_definition)
vim.keymap.set('n', '<leader>K', vim.lsp.buf.hover)
vim.keymap.set('n', '<leader>gr', require('telescope.builtin').lsp_references)
vim.keymap.set('n', '<leader>ds', require('telescope.builtin').lsp_document_symbols)
